### ISSUE TITLE
Panic on current install instructions

### ISSUE THREAD

**Issue by sjl2** [dmlittle/scenery#12]
**This has been resolved already. Posting for posterity.**

## Issue

When running the install instructions, I get the following panic.

```sh
$ go get github.com/dmlittle/scenery
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x1d8727b24e53 pc=0xa7939]

runtime stack:
runtime.throw(0x5e6640, 0x2a)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.(*gcWork).put(0xc820021220, 0xc8204a1950)
        /usr/local/go/src/runtime/mgcwork.go:87 +0x49
runtime.greyobject(0xc8204a1950, 0x0, 0x0, 0xc81ffdaf35, 0x2, 0xd7ec28, 0xc820021220)
        /usr/local/go/src/runtime/mgcmark.go:1015 +0x2f1
runtime.shade(0xc8204a1950)
        /usr/local/go/src/runtime/mgcmark.go:953 +0x9a
runtime.gcmarkwb_m(0xc820412818, 0xc8204a1950)
        /usr/local/go/src/runtime/mbarrier.go:91 +0xc1
runtime.writebarrierptr_nostore1.func1()
        /usr/local/go/src/runtime/mbarrier.go:117 +0x134
runtime.systemstack(0xc820020000)
        /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc1.go:668

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820138230 sp=0xc820138228
runtime.writebarrierptr_nostore1(0xc820412818, 0xc8204a1950)
        /usr/local/go/src/runtime/mbarrier.go:118 +0x71 fp=0xc820138268 sp=0xc820138230
runtime.writebarrierptr(0xc820412818, 0xc8204a1950)
        /usr/local/go/src/runtime/mbarrier.go:137 +0x4b fp=0xc820138298 sp=0xc820138268
os.NewFile(0x3, 0xc8204a1680, 0x2b, 0xc800000000)
        /usr/local/go/src/os/file_unix.go:54 +0x11c fp=0xc8201382f0 sp=0xc820138298
os.OpenFile(0xc8204a1680, 0x2b, 0x0, 0xc800000000, 0x3b, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:109 +0x2ba fp=0xc820138368 sp=0xc8201382f0
os.Open(0xc8204a1680, 0x2b, 0xc82000a1b7, 0x0, 0x0)
        /usr/local/go/src/os/file.go:246 +0x48 fp=0xc8201383a8 sp=0xc820138368
io/ioutil.ReadDir(0xc8204a1680, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:101 +0x64 fp=0xc820138430 sp=0xc8201383a8
go/build.(*Context).readDir(0x7b9a80, 0xc8204a1680, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/go/build/build.go:175 +0xa7 fp=0xc820138470 sp=0xc820138430
go/build.(*Context).Import(0x7b9a80, 0xc8203d74f1, 0x2, 0xc8203e27b0, 0x2c, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/go/build/build.go:614 +0x1158 fp=0xc820138f08 sp=0xc820138470
main.loadImport(0xc8203d74f1, 0x2, 0xc8203e27b0, 0x2c, 0xc8203c3000, 0xc82013bb90, 0xc8203cb8b0, 0x2, 0x2, 0x1, ...)
        /usr/local/go/src/cmd/go/pkg.go:344 +0x687 fp=0xc8201391f0 sp=0xc820138f08
main.(*Package).load(0xc8203c3000, 0xc82013bb90, 0xc820374f00, 0x0, 0x0, 0x4)
        /usr/local/go/src/cmd/go/pkg.go:900 +0x42e1 fp=0xc820139a50 sp=0xc8201391f0
main.loadImport(0xc820151c11, 0x3, 0xc82013df00, 0x3d, 0xc82016e000, 0xc82013bb90, 0xc820158c30, 0x1, 0x1, 0x1, ...)
        /usr/local/go/src/cmd/go/pkg.go:375 +0xd67 fp=0xc820139d38 sp=0xc820139a50
main.(*Package).load(0xc82016e000, 0xc82013bb90, 0xc8200e0900, 0x0, 0x0, 0x4)
        /usr/local/go/src/cmd/go/pkg.go:900 +0x42e1 fp=0xc82013a598 sp=0xc820139d38
main.loadImport(0xc820158691, 0x23, 0xc82013d540, 0x35, 0xc820141c00, 0xc82013bb90, 0xc8201586f0, 0x1, 0x1, 0x1, ...)
        /usr/local/go/src/cmd/go/pkg.go:375 +0xd67 fp=0xc82013a880 sp=0xc82013a598
main.(*Package).load(0xc820141c00, 0xc82013bb90, 0xc8200e0600, 0x0, 0x0, 0x4)
        /usr/local/go/src/cmd/go/pkg.go:900 +0x42e1 fp=0xc82013b0e0 sp=0xc82013a880
main.loadImport(0x7ffeefbff157, 0x1b, 0xc8200121a4, 0x19, 0x0, 0xc82013bb90, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/cmd/go/pkg.go:375 +0xd67 fp=0xc82013b3c8 sp=0xc82013b0e0
main.loadPackage(0x7ffeefbff157, 0x1b, 0xc82013bb90, 0x0)
        /usr/local/go/src/cmd/go/pkg.go:1572 +0x13c3 fp=0xc82013b6d8 sp=0xc82013b3c8
main.download.func1(0x7ffeefbff157, 0x1b, 0x0, 0x55555555555555)
        /usr/local/go/src/cmd/go/get.go:173 +0x43 fp=0xc82013b738 sp=0xc82013b6d8
main.download(0x7ffeefbff157, 0x1b, 0x0, 0xc82013bb90, 0x0)
        /usr/local/go/src/cmd/go/get.go:178 +0xb5 fp=0xc82013bb00 sp=0xc82013b738
main.runGet(0x7b2ac0, 0xc82000a470, 0x1, 0x1)
        /usr/local/go/src/cmd/go/get.go:97 +0x1b5 fp=0xc82013bc40 sp=0xc82013bb00
main.main()
        /usr/local/go/src/cmd/go/main.go:181 +0x782 fp=0xc82013bf30 sp=0xc82013bc40
runtime.main()
        /usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc82013bf80 sp=0xc82013bf30
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc82013bf88 sp=0xc82013bf80

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

## Resolution
Turns out, my global version of `go` was 1.5.4.

```sh
$ go version
go version go1.5.4 darwin/amd64
```

Upgrading to `go1.11.1` fixed the issue. This is just the most recent version, and I'm not sure which version is the minimum one that `scenery` or `go get` supports.

**Comment by sjl2** [comment]
Closing issue since this has been resolved.
